# Numpy

Numpy is a library which provides support for large, homogeneous, multi-dimensional arrays and matrices

In [6]:
# import numpy

import numpy as np

## Creating Arrays in Numpy
### Creating an array from a list

In [5]:
list1 = [10, 20, 30]

list1

[10, 20, 30]

In [9]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [11]:
type(arr1)

numpy.ndarray

### Using arange to create an array

The difference between array and arange is that array takes in a list and turns it into an array, whereas arrange creates an array from a range of numbers.

In [12]:
arr2 = np.arange(10, 20, 1) # (Start, Stop, Step-Size)

In [13]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays

### Two-dimensional arrays

When we combine arrays, together we can add dimensions. Combining two arrays gives us a 2D array!

This creates a matrix for us on which we can perform matrix operations.

In [14]:
# Let's create a new list to join onto the first list
list2 = [40,50,60]

# Join the lists
list3 = [list1, list2]

# Create an array out of the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
# Let's find the shape of that array
# We have a 2D array with 2 elements in the first instance and 3 in the second

arr3.shape

(2, 3)

## Three-Dimensional arrays

In [17]:
arr3dim= np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])

In [19]:
arr3dim.shape

(2, 2, 3)

In [20]:
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

## Using Arrays and Scalars

Numpy arrays (or ndarray) allow us to perform matrix operations.

In [21]:
# For example, we can use simple multiplication

arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [25]:
# How is this different from multiplying a list?
list1 * 3

# When multiplying a standard Python list by an integer, it repeats the contents of the list

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [26]:
# We can multiply an array with another array

# Create a new array with the same size as arr1
arr11 = np.array(list2)

# Multiply the arrays
arr1 * arr11

array([ 400, 1000, 1800])

### Can we multiply arrays of different shapes?

In [29]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

The answer is NO

### It is possible to multiply arrays of different dimensions, but the need the same element size!

In [30]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

## Create ndarrays of the following sizes:
One dimensional array with 12 elements (12,)
Two dimensional array size (3, 4)
Three dimensional array size (2, 5, 4)
Check the size of your ndarray to ensure it is correct

In [55]:
arr12 = np.linspace(0, 10, 12) # 1D 12 elements

arr34 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr34.shape


arr254 = np.arange(40).reshape(2, 5, 4)
arr254.shape

(2, 5, 4)

### Accessing the values inside ndarrays

Let's take arr3 as our example, this was a 2D array

In [65]:
# How can we access the 60?
print(arr3)

# We can use indexing
print(arr3[1][2])

# We ccan also just use a comma
print(arr3[1,2])

[[10 20 30]
 [40 50 60]]
60
60


In [66]:
# How can you get the bottom "row" of this ndarray
arr3[1]

array([40, 50, 60])

In [67]:
# How about if we just want the last column
arr3[:,2]

array([30, 60])

## Statistical functions and arrays

There are a number of built-in statistical functions we can use in numpy


In [68]:
# Finding the sum of all values
arr3.sum()

np.int64(210)

In [69]:
# Finding the sum of all columns
arr3.sum(0)

array([50, 70, 90])

In [72]:
# Finding the sum of all rows
arr3.sum(1)

array([ 60, 150])

In [73]:
# Finding the mean
arr3.mean()

np.float64(35.0)

In [74]:
# Finding the standard deviation
arr3.std()

np.float64(17.07825127659933)

In [75]:
# Finding the variance
arr3.var()

np.float64(291.6666666666667)

In [76]:
# Finding the min value
arr3.min()

np.int64(10)

In [77]:
# Finding the max value
arr3.max()

np.int64(60)

## Iterating through arrays

In [78]:
# For 1D array
for x in arr1:
    print(x)

10
20
30


In [80]:
# How about an n-dimensional array? Use nested loops
for dim in arr3:
    for num in dim:
        print(num)

# This case is for a 2D array - ie. 2 loops needed

10
20
30
40
50
60


In [84]:
# You ccan use nditer to do this instead! (nd-iterate)
# This can be used in simple scenarios, and very complex ones
# It tends to be much cleaner than nested loops

for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


## Saving and loading in numpy


In [85]:
# To save an array as a file
np.save("new", arr3)

In [86]:
# To load an array as a file
np.load("new.npy")

array([[10, 20, 30],
       [40, 50, 60]])

In [87]:
# Saving it as a .txt
np.savetxt("new.txt", arr3, delimiter=",")

In [88]:
# Loading a txt
np.loadtxt("new.txt", delimiter=",")

array([[10., 20., 30.],
       [40., 50., 60.]])